### ISSUE TITLE
param-names fixer breaks code functionality

### ISSUE THREAD

**Issue by adrianmcli** [xjamundx/eslint-plugin-promise#145]
### Description

The fixer for the `param-names` rule breaks code functionality.

The fixer renames arguments in a Promise constructor function, but does not propagate the name change to the calling code.

### Steps to Reproduce

Run the ESLint fixer on the following code:

```js
new Promise((yes, no) => { yes("hello") })'
```

**Expected behavior:**

```js
new Promise((resolve, reject) => { resolve("hello") })'
```

**Actual behavior:**

```js
new Promise((resolve, reject) => { yes("hello") })'
```

### Additional Information

Rather than trying to change people's code, I think it's better to remove the fixer rather than change variable names everywhere.

**Comment by adrianmcli** [comment]
Can submit a PR for this if we can agree that it's better to remove the fixer.

**Comment by macklinu** [comment]
Removing the fixer sounds like a good idea. Thanks for pointing this out - PR welcome for that!

**Comment by adrianmcli** [comment]
Sounds good! Working on it now.

**Comment by adrianmcli** [comment]
@macklinu PR submitted: #146
