### ISSUE TITLE
Disallow the promise constructor

### ISSUE THREAD

**Issue by benjamingr** [xjamundx/eslint-plugin-promise#148]
Hey - first of all great plugin!

Would be great to have a rule that disallows the promise constructor.

A good second alternative is a rule to disallow chaining promises inside the promise constructor.

This is to avoid [explicit construction](https://stackoverflow.com/questions/23803743/what-is-the-explicit-promise-construction-antipattern-and-how-do-i-avoid-it) which is the most common code style error with promises.

On a tangent - I'm on holiday, but if any of you are up for participating in the promises-debugging team at Node.js that'd be very welcome :)

**Comment by macklinu** [comment]
I believe we have a rule for what you're looking for (disallowing the promise constructor) - [`avoid-new`](https://github.com/xjamundx/eslint-plugin-promise/blob/master/rules/avoid-new.js).

I think your second suggestion is an interesting one that would be good to figure out how to represent in an ESLint rule. 😄

**Comment by xjamundx** [comment]
Closing because i think this is covered by `avoid new`. Please reopen if we missed something!
