### ISSUE TITLE
Broken html report doc link

### ISSUE THREAD

**Issue by MarcusLindberg123** [xjamundx/eslint-plugin-promise#176]
### Description

Generating a html report with warnings result in broken links

### Steps to Reproduce

1. eslint -f html
2. Press warning link.

**Expected behavior:** [What you expect to happen]
Goes to doc page

**Actual behavior:** [What actually happens]
Broken link: 
https://github.com/xjamundx/eslint-plugin-promise/tree/v4.2.1/docs/rules/avoid-new.md

### Versions

- Node version: v10.16.3
    "babel-eslint": "^9.0.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-es-beautifier": "^1.0.1",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.2",
    "eslint-plugin-promise": "^4.2.1"

### Additional Information
eslintrc:
module.exports = {
    "extends": ["airbnb", "plugin:es-beautifier/standard"],
    "plugins": [
        "es-beautifier",
        "promise"
    ],

**Comment by xjamundx** [comment]
I think this works now https://github.com/xjamundx/eslint-plugin-promise/blob/v4.2.1/docs/rules/no-return-wrap.md https://github.com/xjamundx/eslint-plugin-promise/tree/v4.2.1/docs/rules/avoid-new.md
