### ISSUE TITLE
false positive for if-else

### ISSUE THREAD

**Issue by laggingreflex** [xjamundx/eslint-plugin-promise#18]
This gives error

    return promise.resolve(1)
        .then((value) => {
            if (true) {
                return 1;
            } else {
                return 2;
            }
        });
> Each then() should return a value or throw  promise/always-return

Even though it's definitely returning either 1 or 2

**Comment by laggingreflex** [comment]
Poking around, I've found that [the `consistent-return` implementation on eslint does it this way:](https://github.com/eslint/eslint/blob/master/lib/rules/consistent-return.js#L136)

    function checkLastSegment(node) {
        ...
        if (!funcInfo.hasReturnValue ||
            funcInfo.codePath.currentSegments.every(isUnreachable) ||
        ...
    }
    onCodePathEnd: function() {
        funcInfo = funcInfo.upper;
    },
    // Reports a given return statement if it's inconsistent.
    ReturnStatement: function(node) {
        ...
        if (!funcInfo.hasReturn) {
        ...
    },

It seems to rely on more than just `MemberExpression` (which this lib does)

**Comment by xjamundx** [comment]
Thanks for the dive

**Comment by xjamundx** [comment]
I think this is the same issue as #8

**Comment by jcristovao** [comment]
Hey @xjamundx , is there any plans to actually implement this?

**Comment by xjamundx** [comment]
@jcristovao for sure if you can work on it. I'd love the help!

**Comment by jcristovao** [comment]
I am not sure I have the skills :( I'll rephrase the question, what is your opinion on @laggingreflex suggestion?

**Comment by xjamundx** [comment]
@jcristovao I think it sounds like a great idea! I haven't worked with code-path analysis yet, but I can probably get to it in the next few months. Would love it if you could work on this sooner. 

I don't personally use that pattern, so it's not urgent for me, but I'd love your help in building this. I can link you to the docs if you need.
