### ISSUE TITLE
Please create a tag

### ISSUE THREAD

**Issue by noyobo** [xjamundx/eslint-plugin-promise#208]
### Description

Did you forget to create a tag? This will make the address of the vscode link to the document not found.

![image](https://user-images.githubusercontent.com/1292082/105274177-a3d9fa80-5bd7-11eb-9a83-61b579de63d1.png)

`https://github.com/xjamundx/eslint-plugin-promise/tree/v4.2.1/docs/rules/no-return-wrap.md`

**Comment by xjamundx** [comment]
Will check this out later this week, thanks for bringing it up

**Comment by xjamundx** [comment]
I think this is a duplicate of #176, but I'm so out of date with github stuff I don't really know how to do it. I know that sounds stupid. I think I can figure it out though and will try :D

**Comment by xjamundx** [comment]
I know `npm version` will do it

**Comment by xjamundx** [comment]
✅  done! Fixes #176 as well
