### ISSUE TITLE
Promise.all catch or return help

### ISSUE THREAD

**Issue by petitchevalroux** [xjamundx/eslint-plugin-promise#21]
I'm noob to Promises and this is why I REALLY love your plugin ... but I can't figure out why I get this error : 
 5:1  error  Expected catch() or return  promise/catch-or-return
On the following file: 
[sample.txt](https://github.com/xjamundx/eslint-plugin-promise/files/436582/sample.txt)
Using the following .eslintrc:
[eslintrc.txt](https://github.com/xjamundx/eslint-plugin-promise/files/436583/eslintrc.txt)

**Comment by xjamundx** [comment]
My plugin only supports native promises (at the moment), so it doesn't have
any notion of the "done" method that you're using to handle errors.

Not sure on the correct solution, maybe a bluebird version of this rule or
something 🤔

**Comment by petitchevalroux** [comment]
@xjamundx ok i'm so noob that i didn't know done was bluebird specific. Ty for pointing this
