### ISSUE TITLE
Support ESLint 8.x

### ISSUE THREAD

**Issue by MichaelDeBoey** [xjamundx/eslint-plugin-promise#218]
ESLint v8.0.0 is [released](https://eslint.org/blog/2021/10/eslint-v8.0.0-released) 🎉

It would be awesome to have official ESLint 8 support. 👊
I'm happy to help where I can of course 🙂

**Comment by Romick2005** [comment]
![image](https://user-images.githubusercontent.com/17779660/145065485-2f95d3ed-e173-4917-9a18-a1ed4ff2e829.png)

**Comment by doberkofler** [comment]
Support for eslint 8 would be most appreciated.

**Comment by rtrembecky** [comment]
@doberkofler ESLint 8 is supported as of 1.0.8: https://github.com/microsoft/rushstack/blob/master/eslint/eslint-patch/CHANGELOG.md#108
I just went to upgrade my ESLint plugins and configs and I'm running ESLint 8 with `@rushstack/eslint-patch` of 1.1.0 with no issues.

**Comment by xjamundx** [comment]
@MichaelDeBoey what do you actually want me to do here. like just update the dev dep to eslint 8 or is there something else?

**Comment by MichaelDeBoey** [comment]
@xjamundx I have #219 to support ESLint v8, but that PR is dependent on #239
