### ISSUE TITLE
apple clone

### ISSUE THREAD

**Issue by Sandesh333333** [xjamundx/eslint-plugin-promise#232]
### Description

[Description of the issue or feature request]

### Steps to Reproduce

1.  [First Step]
2.  [Second Step]
3.  [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Versions

[Please fill this in if you are submitting a bug report]

- Node version: [Replace this]
- ESLint version: [Replace this]
- eslint-plugin-promise version: [Replace this]

### Additional Information

[Any additional information, configuration or data that might be necessary to
reproduce the issue]

**Comment by xjamundx** [comment]
Some kind of spam issue here.
