### ISSUE TITLE
Update tags and CHANGELOG

### ISSUE THREAD

**Issue by voxpelli** [xjamundx/eslint-plugin-promise#28]
Looks like npm received a `3.0.0` release of this module, but no new tag and no new CHANGELOG entry has been added for this release.

**Comment by xjamundx** [comment]
Ahh yes good call, we shouldn't accept package.json updates in the pull requests directly.

**Comment by xjamundx** [comment]
Will fix right now.

**Comment by niedzielski** [comment]
This issue appears to have popped up again. v3.5 is out but no tags or changelog exists. Consider adding `git push --follow-tags` to the postversion script so that `npm version <patch|minor|major>` automatically pushes the tag. Thanks!

**Comment by niedzielski** [comment]
:+1: o/ Thanks for such a quick fix!
