### ISSUE TITLE
disallow rejecting non-errors

### ISSUE THREAD

**Issue by jonathanong** [xjamundx/eslint-plugin-promise#3]
similar to `throw 'string'`, rejecting anything but an error should be discouraged

**Comment by xjamundx** [comment]
I like that idea. I haven't used promises too too much, but if that's a standard practice I think we should enforce it.

**Comment by xjamundx** [comment]
I like that

**Comment by ForbesLindesay** [comment]
This is definitely standard practice.  It would be a great rule to add.

**Comment by xjamundx** [comment]
So http://eslint.org/docs/rules/no-throw-literal will handle the `throw` case already.

This rule would just be for `Promise.reject(new Error('thing'))` instead of `Promise.reject('thing')` is that right?

**Comment by ForbesLindesay** [comment]
Also `new Promise((resolve, reject) => reject('thing'))`

**Comment by sindresorhus** [comment]
How should it handle custom errors? I suggest it accepts anything that matches `/^(?:[A-Z][a-z0-9]*)*Error$/`.

**Comment by ForbesLindesay** [comment]
It should just follow the same rules as no-throw-literal.  It's fine to do things like `reject(getError())`. All we're trying to do is guard against the common mistake of `reject('Something went wrong')`

**Comment by xjamundx** [comment]
Yep I agree with this. I'll get it in there soon.

**Comment by macklinu** [comment]
It looks like [`prefer-promise-reject-errors`](https://eslint.org/docs/rules/prefer-promise-reject-errors) was added to the ESLint core in v3.14.0, so I'm wondering if this feature request is still relevant to eslint-plugin-promise. Anyone have thoughts on this?

**Comment by macklinu** [comment]
I'm going to close this for now, since [`prefer-promise-reject-errors`](https://eslint.org/docs/rules/prefer-promise-reject-errors) is available in ESLint core. Please comment  if I'm missing something here and eslint-plugin-promise can provide functionality not present in the previously mentioned rule. Thanks!
