### ISSUE TITLE
always-catch: Consider two param `then` as the same as `catch`

### ISSUE THREAD

**Issue by feross** [xjamundx/eslint-plugin-promise#4]
For the `always-catch` rule, I'd like to be able to consider this:

```
myPromise.then(doSomething, catchErrors);
```

as a valid catch, since lots of code that uses `standard` does that.

**Comment by xjamundx** [comment]
@feross Yeah `catch` is maybe slightly better, because it will also catch programmer errors in the `doSomething` code, but it's certainly better than nothing. Maybe I can add an exception or something. Thanks for the idea. Will mull it over a bit.

**Comment by feross** [comment]
Yep, I understand. I just couldn't enable this rule without causing tons of `standard` users' code to fail. If there's a way to just check that there's any catch handler in `then()` or `catch()`, that would be a good candidate to enable for all `standard` users.

**Comment by xjamundx** [comment]
I'll add a configurable exception `"always-catch": [2, { allow-then: true }]`. Think that might work?

**Comment by feross** [comment]
@xjamundx Yep, that'd work.

**Comment by xjamundx** [comment]
K give me a week if it don't forget !

**Comment by xjamundx** [comment]
A lot of people are also saying if the promise is returned it doesn't need
to be caught. I may also add this exception

**Comment by xjamundx** [comment]
Started on this

**Comment by xjamundx** [comment]
Closed by 41f1c02b8f0aac220b4401b68fa466cf03356530

**Comment by feross** [comment]
Nice, will try to release this in standard v7!
