### ISSUE TITLE
Prevent mistakes with `Promise.resolve/reject()`

### ISSUE THREAD

**Issue by sindresorhus** [xjamundx/eslint-plugin-promise#47]
I've seen this mistake a couple of times: https://github.com/avajs/ava/issues/1119#issuecomment-261782231 Nested parens are hard to read and sometimes you wrap the wrong thing. Would be useful to have a rule the reported when you tried using more than one argument with `Promise.resolve()` or `Promise.reject()`.

**Comment by jfmengels** [comment]
That sounds like a good addition, but you could generalize that to all Promise functions.
- 0 or 1 argument to `Promise.resolve()`/`Promise.reject()`
- 1 argument to `new Promise()`
- 1 or 2 arguments to `.then()`
- 1 argument to `.catch()`
- 1 argument to `Promise.all()`
- etc...

**Comment by macklinu** [comment]
I'd be interested in contributing this. Would this be a new rule, perhaps named `valid-params`? Any other thoughts on requirements for this rule?

**Comment by macklinu** [comment]
I'm working on this currently and hope to have a PR up later today 😄

**Comment by alexilyaev** [comment]
@macklinu Will it include `1 argument to Promise.all()` check?

I've just had an issue with some code that passed 2 arguments to `Promise.all` instead of an array of 2 items, and it took me a long time to find it.

Will your PR cover it, or should I open a new ticket?

**Comment by macklinu** [comment]
Yep, 1 argument to `Promise.all()` is covered in #85. 👍

**Comment by macklinu** [comment]
Just shipped v3.7.0 - please update and report any issues you find with this new rule. Thanks!
