### ISSUE TITLE
Are there any plans for an eslint-config-promise?

### ISSUE THREAD

**Issue by TheBeardedLlama** [xjamundx/eslint-plugin-promise#48]
it'd be nice to not have to explicitly include the rules in the config

**Comment by xjamundx** [comment]
Do you know if you can easily combine rules/config? I wouldn't mind providing a reference rule-set, but not as a separate module/repo.

**Comment by TheBeardedLlama** [comment]
I think the way it's done is via a module, but I only skim-read the instructions...

http://eslint.org/docs/developer-guide/shareable-configs

**Comment by TheBeardedLlama** [comment]
I'd be happy to do the legwork if that's the issue

**Comment by xjamundx** [comment]
It'd be more like this:
http://eslint.org/docs/developer-guide/working-with-plugins#configs-in-plugins

**Comment by TheBeardedLlama** [comment]
that still talks about publishing on npm though...

**Comment by sindresorhus** [comment]
You can bundle a recommended config, see: https://github.com/sindresorhus/eslint-plugin-unicorn/blob/9357b57a11bccb754a4b58f1b526cdf22f2977af/index.js#L7

**Comment by TheBeardedLlama** [comment]
closing as there's an RFC for this now
