### ISSUE TITLE
Support eslint v4

### ISSUE THREAD

**Issue by evilebottnawi** [xjamundx/eslint-plugin-promise#63]

**Comment by xjamundx** [comment]
PRs welcome!

**Comment by macklinu** [comment]
I opened #76 to address updating to ESLint v4.

> plugin don't have eslint as peer deps, it is bad, should we fix this?

I think this could be part of another PR, or #76 if that makes sense. For example, [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react/blob/f7441bb41e4a916b4d5b1b22b136515024f18d65/package.json#L39-L41) sets the following in their `package.json`:

```json
"peerDependencies": {
  "eslint": "^3.0.0 || ^4.0.0"
}
```

**Comment by macklinu** [comment]
Looks like the peer dependency on ESLint was removed in https://github.com/xjamundx/eslint-plugin-promise/pull/40, so I'm not sure about including it in this plugin right now. At some point down the road, if we have to depend on newer ESLint APIs, we can reconsider this.
