### ISSUE TITLE
If a function ever returns a Promise, it should always return a Promise

### ISSUE THREAD

**Issue by dr-impossible** [xjamundx/eslint-plugin-promise#64]
### Rule: `consistent-promise-function`
Ensure that if a function returns a Promise, it should consistently return a Promise. Instead of throwing an exception, it should return a rejected Promise

#### Valid
```javascript
function myPromiseMethod(condition) {
  if (condition) {
    return Promise.resolve("some value");
  } else {
    return Promise.reject(new Error("Invalid result"));
  }
}

function myNormalMethod(condition, otherCondition) {
  if (condition) {
    return "some value";
  } else {
    if (otherCondition) {
      throw new Error("some problem");
    }
    return "some other value";
  }
}
```

#### Invalid
```javascript
function badMethod(condition, otherCondition) {
  if (condition) {
    return Promise.resolve("some value");
  } else if (otherCondition) {
    return "other value";
  } else {
    throw new Error("Invalid condition");
  }
}
```

**Comment by xjamundx** [comment]
I'm not against the rule, but I have a questions/concerns:

1. I personally prefer `throw` to `return Promise.reject`
2. Why not enforce `no-throw` consistently instead of on a per function basis?
3. What do you do in this case?

```js
function badMethod(condition, otherCondition) {
  if (condition) {
    return getPromise(); // a valid promise
  } else if (otherCondition) {
    return "other value";
  } else {
    throw new Error("Invalid condition");
  }
}
```

**Comment by dr-impossible** [comment]
1. if it's a function that's in a then() handler, then `throw` would definitely make sense. This would align with async/await
2. I guess 1 & 3 will sort of answer this one
3. Come to think of it, enforcing this rule would even be possible with eslint. I think you might need something that can do type checking.

**Comment by macklinu** [comment]
I'm stumped as to how to go about resolving this. It might be impossible or very difficult to enforce this with ESLint. A type checker like Flow or TypeScript might be a better tool for this problem.

I'm going to close this for now, but feel free to reopen if you have ideas on how to resolve (PRs are welcome!).
