### ISSUE TITLE
rule to prefer new Promise over Promise.defer/pending

### ISSUE THREAD

**Issue by twk-b** [xjamundx/eslint-plugin-promise#72]
Need a new rule to prefer new Promise over Promise.defer/pending. 

Could be an extension of promise/avoid-new because it is the opposite behaviour. 

Should stop:

var Q = Promise.pending();
return Q.promise;

and

var Q = Promise.defer();
// stuff with Q.resolve() or Q.reject()
return Q.promise;

and the --fix would replace 

var Q = Promise.defer();
// stuff with Q.resolve() or Q.reject()
return Q.promise;

with

return new Promise(resolve, reject) {
// replacing Q.resolve/Q.reject with just resovle/reject
});

**Comment by xjamundx** [comment]
The thing is.....`Promise.defer` isn't even really offical ES6 syntax.

Shouldn't we just ban `q` / `bluebird` instead?

**Comment by twk-b** [comment]
As you suggest, Promise.defer is not valid ES6, so the linter should be
catching it.

Our use case is we are mostly ES5, migrating to ES6, so switching to the
standard promise syntax is another step forward. We cannot remove bluebird
entirely at this point. We have developers familiar with writing the  older
syntax and want to encourage them to use new Promise instead. Previously we
had promise/avoid-new set, so we have almost none of the new format.

**Comment by xjamundx** [comment]
So possibly a generic rule that bans any non-standard `Promise.` syntax?

**Comment by twk-b** [comment]
Yes, exactly, with Promise.defer() and Promise.pending() being top of that
list.

**Comment by xjamundx** [comment]
Yeah so probably what we'd do is simply whitelist a handful of command `Promise.all` `Promise.race` `Promise.resolve` and `Promise.reject` (Did I miss anything?) and warn with everything else. Sound reasonable?

**Comment by twk-b** [comment]
Sounds reasonable.

Checking our codebase, the other two we are using are: .reduce, .map and of
course Promise() itself. Not sure if map and reduce are in ES6...

**Comment by xjamundx** [comment]
Check this out. I think this is basically what your'e looking for!
http://astexplorer.net/#/gist/70dbfbd23c27df3515405ff338b4e7c9/ec711161bc273221eaf3168b53022319ea8def18

**Comment by xjamundx** [comment]
I guess technically `bind`, `toString`, `apply` and `call` are all valid, but super weird to use in this context.

**Comment by twk-b** [comment]
LGTM.

http://astexplorer.net/
<http://astexplorer.net/#/gist/70dbfbd23c27df3515405ff338b4e7c9/ec711161bc273221eaf3168b53022319ea8def18>
is
a find for me, thanks for the pointer. Maybe next time I will try a PR.

thanks
-b

**Comment by macklinu** [comment]
I'm going to close this and continue discussion in #46, which is a similar proposal.
