### ISSUE TITLE
no-async-without-await plugin

### ISSUE THREAD

**Issue by chrisblossom** [xjamundx/eslint-plugin-promise#74]
It might be a good idea to merge [zertosh/eslint-plugin-no-async-without-await](https://github.com/zertosh/eslint-plugin-no-async-without-await) into this plugin. Seems like a good fit. Thoughts?

**Comment by xjamundx** [comment]
Sure, though I don't really agree with the premise. For example sometimes this is nice

```
let horse = async () { return "neh" }

// as an alternative to:
let horse = () => Promise.resolve("neh")
```

**Comment by macklinu** [comment]
I'm not sure I want to bring that functionality into this ESLint plugin. There's also a discussion in the ESLint repo for a similar request (https://github.com/eslint/eslint/issues/9787) that is talking about the difficulty of properly enforcing this with a linter (a type system would be ideal for this).

I'm going to close this for now. Thank you for the suggestion though!
