### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by macklinu** [xjamundx/eslint-plugin-promise#84]
I think it would be nice to add some information to help potential contributors set up their environments, tips for running tests, etc.

For example, I set up a Node 4 environment for development (since that is the primary testing environment on Travis).

I also find it easier to watch a specific test when developing a new rule so I am only running the tests pertaining to my lint rule: `mocha test/my-rule.js --watch`. Perhaps that could be something to include in this document?

I'm not sure what sort of guidelines to include based on the past experience of this project, so I'd appreciate feedback from maintainers and other contributors. I'd be glad to propose a `CONTRIBUTING.md` PR to get more conversation started, if that would help. 👍

**Comment by macklinu** [comment]
Following up from #86, it would be nice to use Node 8 and npm 5 (or even yarn) for local development, as it would allow us to use dev tools like [lint-staged](https://github.com/okonet/lint-staged) (which is dropping support for Node 4 in an upcoming release - https://github.com/okonet/lint-staged/issues/372). I still think it's valuable to write Node 4 compatible code and test it on CI, but developing with Node 8 locally would be an improvement and could be documented in the `CONTRIBUTING.md` file.

**Comment by xjamundx** [comment]
I like node 8 locally. I don't mind node 4 support (for now).

I prefer to use npm5 over yarn
