### ISSUE TITLE
Accept yield in catch-or-return

### ISSUE THREAD

**Issue by simonratner** [xjamundx/eslint-plugin-promise#9]
Yielding promises is common when using [tj/co](https://github.com/tj/co) or similar constructs.
For example:
```js
co(function * g () {
  let status = yield getResult().then((result) => result.status)
})
```

**Comment by xjamundx** [comment]
@simonratner this rule only enforces things explicitly inside the `then()` and `catch()` block, so I'm thinking `yield` won't really apply in those situations? Let me know if you have some example that might cause an issue.

**Comment by simonratner** [comment]
Looks like it currently works as-is, as the expression:
```js
yield getResult().then()
```
is classified as a `YieldExpression` rather than a `CallExpression`, so the rule doesn't match, presumably for the same reason why `return` doesn't match. I was going purely off the docs, which I guess could use more precision:
```
Ensure that each time a then() is applied to a promise, a catch() is applied as well. 
Exceptions are made if you are returning that promise.
```
Feel free to close.

**Comment by xjamundx** [comment]
So it looks like this works by accident, but could probably use some tests @simonratner any chance you can submit a PR with a few test cases?
