### ISSUE TITLE
Update code formatting tools

### ISSUE THREAD

**Issue by macklinu** [xjamundx/eslint-plugin-promise#95]
#91 introduced an ESLint config to validate the ESLint rules, and as a result, this codebase now uses Standard (formatting and linting) as well as ESLint (linting).

https://github.com/xjamundx/eslint-plugin-promise/pull/91#issuecomment-364181144 makes a good point that Standard is ESLint under the hood, so some options I see moving forward:

* update the ESLint config to extend [`eslint-config-standard`](https://github.com/standard/eslint-config-standard) and stop executing the `standard` CLI tool altogether
* migrate to [Prettier](http://prettier.io/) for code formatting, and use ESLint strictly for code linting

As a personal preference and having more experience with Prettier, I would choose the latter. I prefer having a file formatted the same way across IDEs and computers, either by saving a file or formatting in a precommit hook - standard doesn't necessarily enforce consistent line length and bracket spacing, from my experience.

Either way, part of resolving this issue would be to introduce [lint-staged](https://github.com/okonet/lint-staged) into the codebase, so that code formatting and linting would run as a precommit hook.

I will leave this open for a bit in case other contributors/maintainers have anything to add.

**Comment by xjamundx** [comment]
Yeah I love prettier
